-- MySQL Script generated by MySQL Workbench
-- 05/12/15 23:40:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema maraton
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema maraton
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `maraton` ;
USE `maraton` ;

-- -----------------------------------------------------
-- Table `maraton`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maraton`.`pais` (
  `codigo` CHAR(3) NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  `continente` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maraton`.`corredor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maraton`.`corredor` (
  `id_corredor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NULL,
  `ano_nacimiento` INT NULL,
  `categoria` VARCHAR(45) NULL,
  `codigo_pais` CHAR(3) NULL,
  `club` VARCHAR(45) NULL,
  `sexo` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_corredor`),
  UNIQUE INDEX `id_corredor_UNIQUE` (`id_corredor` ASC),
  INDEX `codigo_idx` (`codigo_pais` ASC),
  CONSTRAINT `codigo`
    FOREIGN KEY (`codigo_pais`)
    REFERENCES `maraton`.`pais` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maraton`.`resultado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maraton`.`resultado` (
  `id_resultado` INT NOT NULL AUTO_INCREMENT,
  `general` INT NULL,
  `sexo` INT NULL,
  `categoria` INT NULL,
  `total_general` INT NULL,
  `total_sexo` INT NULL,
  `total_categoria` INT NULL,
  PRIMARY KEY (`id_resultado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maraton`.`tipo_deporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maraton`.`tipo_deporte` (
  `id_tipo_deporte` INT NOT NULL,
  `distancia` INT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tipo_deporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maraton`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maraton`.`carrera` (
  `id_carrera` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `tipo_deporte` INT NOT NULL,
  `lugar` VARCHAR(100) NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`id_carrera`),
  INDEX `id_tipo_deporte_idx` (`tipo_deporte` ASC),
  CONSTRAINT `id_tipo_deporte`
    FOREIGN KEY (`tipo_deporte`)
    REFERENCES `maraton`.`tipo_deporte` (`id_tipo_deporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maraton`.`parical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maraton`.`parical` (
  `id_parcial` INT NOT NULL AUTO_INCREMENT,
  `km` INT NULL,
  `tiempo_oficial` TIME NULL,
  `tiempo_neto` TIME NULL,
  `ritmo` FLOAT NULL,
  `velocidad` FLOAT NULL,
  `puesto` INT NULL,
  `corredor` INT NULL,
  `carrera` INT NULL,
  PRIMARY KEY (`id_parcial`),
  INDEX `id_corredor_idx` (`corredor` ASC),
  INDEX `id_carrera_idx` (`carrera` ASC),
  CONSTRAINT `id_corredor`
    FOREIGN KEY (`corredor`)
    REFERENCES `maraton`.`corredor` (`id_corredor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_carrera`
    FOREIGN KEY (`carrera`)
    REFERENCES `maraton`.`carrera` (`id_carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `maraton`.`corredor_carrera_resultado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maraton`.`corredor_carrera_resultado` (
  `id_corredores_carreras` INT NOT NULL AUTO_INCREMENT,
  `corredor` INT NOT NULL,
  `carrera` INT NOT NULL,
  `resultado` INT NULL,
  `dorsal` INT NOT NULL,
  PRIMARY KEY (`id_corredores_carreras`),
  INDEX `id_resultado_idx` (`resultado` ASC),
  INDEX `id_carrera_idx` (`carrera` ASC),
  INDEX `id_corredor_idx` (`corredor` ASC),
  UNIQUE INDEX `id_corredores_carreras_UNIQUE` (`id_corredores_carreras` ASC),
  CONSTRAINT `idcorredor`
    FOREIGN KEY (`corredor`)
    REFERENCES `maraton`.`corredor` (`id_corredor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idcarrera`
    FOREIGN KEY (`carrera`)
    REFERENCES `maraton`.`carrera` (`id_carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idresultado`
    FOREIGN KEY (`resultado`)
    REFERENCES `maraton`.`resultado` (`id_resultado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
